### ISSUE TITLE
Cannot compile 32 bit with Microsoft Windows SDK v7.0

### ISSUE THREAD

**Issue by duncanmcbryde** [duncanmcbryde/PicoPy#1]
start compile with v7.0 CMD shell

> set DISTUTILS_USE_SDK=1
> setenv /x86 /release

Cannot find the included stdint.h file

> include\4k\PicoStatus.h(15) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory
> error: command 'C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\Bin\cl.exe' failed with exit status 2

**Comment by duncanmcbryde** [comment]
Result of Anaconda switching from python 2.7  to python 3.5 in environment on my system. Why does environment change?

**Comment by duncanmcbryde** [comment]
Fixed issue by opening a new SDK v7.0 CMD shell. Fails using 64 bit Python, need to use 32 bit python for compilation.
